### PR TITLE
Removed inline setting for NavTitle, removed nil coalescing, added tests

### LINKED ISSUE #131: Home view large title truncates if name is large.
**Describe the bug**
Home view large title truncates if full name is entered.

**To Reproduce**
1. Edit and enter full name in profile.
2. Go to Home View.  
3. See title of home view.

**Expected behavior**
The title should not truncate and entire title should be legible.

**Screenshots**
| Truncating Title ❌|
| ------------- | 
| |

**Smartphone (please complete the following information):**
- Simulator: iPhone 11 Pro
- OS: iOS 13.7
- Xcode 11.7

**Additional context**
One probable fix is to is to consider only first name (i.e first word of name string) for the title here.

### PR DESCRIPTION
**Pull request by R-Cole**
### Description
Removed inline setting for NavTitle, removed nil coalescing, added tests
Fixes #131

simulator_screenshot_issue_133

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
 
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
  
### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
 
**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by R-Cole** [comment]
I tried amending previous PR without success, sorry for new pr. Looks like Travis is happy now.

**Comment by yugantarjain** [comment]
Hi @R-Cole, great work! I'm approving this PR. 
However, can you do a final self-check? Also, can you remove the space in '# 131' in the description. Thanks!

**Review by yugantarjain — APPROVED** [review]

**Comment by R-Cole** [comment]
@yugantarjain Thx! Glad I could help out. 
I removed the space in the pr description. 
Just wondering if there is any special protocol for self-tests? I did perform self-tests that were the same as my unit tests.

**Comment by yugantarjain** [comment]
> @yugantarjain Thx! Glad I could help out.
> I removed the space in the pr description.
> Just wondering if there is any special protocol for self-tests? I did perform self-tests that were the same as my unit tests.

Nothing special, just a manual self check. And then you can tick those boxes in the PR description.

**Review by sunjunkie — APPROVED** [review]
Looks good. Thanks to you both!

**Pull request merged**
