### PR TITLE
chore: Basic Travis CI integration

### LINKED ISSUE #38: Integrate Travis CI
As a developer I want to integrate Travis CI so I could not merge when test fails.

### PR DESCRIPTION
**Pull request by annabauza**
### Description
Travis CI integration

Fixes #38

### Type of Change:
- Quality Assurance

### How Has This Been Tested?
by Travis CI 

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
@annabauza We need to set up a gitignore file first. Some of these files are your settings and shouldn't be under source control. I can create one (but not til tomorrow).

**Comment by annabauza** [comment]
Yep I'm not sure which ones because Travis was failing due to wrong scheme config. Do you know which one?  I will remove and will check Travis then. Thanks.

**Comment by annabauza** [comment]
@sunjunkie

**Comment by sunjunkie** [comment]
> Yep I'm not sure which ones because Travis was failing due to wrong scheme config. Do you know which one? I will remove and will check Travis then. Thanks.

Remove Files with xcuserdata in the path.

**Comment by annabauza** [comment]
@sunjunkie done, Thank you!

**Pull request merged**
