### PR TITLE
feat: Members Search

### LINKED ISSUE #26: As a user I would like to search the members, so I could quickly find a particular user.

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR implements searching of members in the members list screen. Both UI and backend consumption have been done.

Fixes #26 

### Mocks
image

### Type of Change:
- Code
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on Xcode Simulator.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by vatsalkul** [comment]
User interface and Experience wise it is not looking good. I know that Swift UI do not offer SearchBar view out of the box, can you use a UIKit Search bar in SwiftUI. You just need to implement struct SearchBar: UIViewRepresentable.
Here is a nice article about it. [Article](https://medium.com/@axelhodler/creating-a-search-bar-for-swiftui-e216fe8c8c7f)

**Comment by sunjunkie** [comment]
> User interface and Experience wise it is not looking good. I know that Swift UI do not offer SearchBar view out of the box, can you use a UIKit Search bar in SwiftUI. You just need to implement struct SearchBar: UIViewRepresentable.
> Here is a nice article about it. [Article](https://medium.com/@axelhodler/creating-a-search-bar-for-swiftui-e216fe8c8c7f)

@vatsalkul What does "not looking good" mean?

**Comment by vatsalkul** [comment]
@sunjunkie search bar should hide when we scroll downwards. It should have ‘x’ button to dismiss search and reload main data. When we search we are making a network call, when clicking on x button we should load the initial data that was present when tapping on members tab

**Comment by vatsalkul** [comment]
It can be achieved easily by using UIKIT search bar UIViewRepresentable, like it was used to show maps. Let me know if you have better solution

**Comment by sunjunkie** [comment]
@yugantarjain This is a good start. The search subview needs to be more iOS-like. My comments so far:

1. There needs to be a little "x" icon (clear button) in the search field. User should not have to backspace to clear the search. 
2. You need to use a Search button (which is standard ios) rather than an arrow icon. 
3. The search should also be activated by the return key.
4. How about a response like "No member found" if the search results are empty.

**Comment by sunjunkie** [comment]
> @sunjunkie search bar should hide when we scroll downwards. It should have ‘x’ button to dismiss search and reload main data. When we search we are making a network call, when clicking on x button we should load the initial data that was present when tapping on members tab

Agreed. Just confirming. The feedback was very vague and therefore not really actionable. 😊

**Comment by vatsalkul** [comment]
> > @sunjunkie search bar should hide when we scroll downwards. It should have ‘x’ button to dismiss search and reload main data. When we search we are making a network call, when clicking on x button we should load the initial data that was present when tapping on members tab
> 
> Agreed. Just confirming. The feedback was very vague and therefore not really actionable. 😊

Didn’t understand this!

**Comment by vatsalkul** [comment]
@sunjunkie points that you have suggested can be easily achieved by using ViewRepresentable to use UIKit search bar

**Comment by yugantarjain** [comment]
Okay, will do.

**Comment by annabauza** [comment]
We spoke before that iOS has specific expectations. Please implement what we agree for @yugantarjain.

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers PR has been updated. Updates - 

1. UISearchBar has been wrapped and used.
2. Features 'x' button to clear text, and automatically hiding/showing 'Cancel' button.
3. Keyboard features search button which is used to search instead of old arrow button.
4. Shows 'No member found' message when search results are empty.

**Comment by vatsalkul** [comment]
@yugantarjain It's looking great so far. But you have not done the implementation of How the app will show original result when I am done searching?
My suggestion: When a user tapped cancel or "x" you can load the initial membersResponseData.

When search starts, you are removing membersResponseData, what I'll suggest is to make new array to show the members we received from the server after searching and when user cancels the search, show the original membersResponseData. (which reduces the network call the fetch original list of members) Does it make sense! 😇

Can you hide the search bar when scrolling down, as shown [here](https://drive.google.com/file/d/1IunfqTNs5ATINcBWsRgT1W7t6GX-mM41/view?usp=sharing)

**Comment by yugantarjain** [comment]
> @yugantarjain It's looking great so far. But you have not done the implementation of How the app will show original result when I am done searching?
> My suggestion: When a user tapped cancel or "x" you can load the initial membersResponseData.
> 
> When search starts, you are removing membersResponseData, what I'll suggest is to make new array to show the members we received from the server after searching and when user cancels the search, show the original membersResponseData. (which reduces the network call the fetch original list of members) Does it make sense! 😇
> 
> Can you hide the search bar when scrolling down, as shown [here](https://drive.google.com/file/d/1IunfqTNs5ATINcBWsRgT1W7t6GX-mM41/view?usp=sharing)

Okay, will add another array for search results.

Also, about hiding of search bar, is that in SwiftUI or UIKit? I've done a lot of research and haven't found a nice method to do exactly that in SwiftUI. There is [one](http://blog.eppz.eu/swiftui-search-bar-in-the-navigation-bar/), however, it is prone to breakages since it makes assumptions about underlying framework implementations which can be changed...

**Comment by yugantarjain** [comment]
@vatsalkul done.

**Comment by sunjunkie** [comment]
This looks great. But what about tests?

**Comment by yugantarjain** [comment]
> This looks great. But what about tests?

Yes, will start working on them now. I wanted to get a nod on the actual code before writing tests. Thanks

**Comment by vatsalkul** [comment]
Great work @yugantarjain  🎉 I really like the implementation, you can start working on tests.

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers tests have been added.

**Review by ApheleiaS — APPROVED** [review]
Good work on implementation and tests.

**Review by sunjunkie — APPROVED** [review]

**Pull request merged**
