### PR TITLE
feat: All Settings done: change password, logout, delete account

### LINKED ISSUE #54: Hook up Logout UI with backend
## Description
As a user,
I need to be able to logout of the app. 

### Update [Required]
- [ ]  Consume logout backend and logout of session. 
- [ ]  Redirect to login screen 
- [ ] Decide whether to Logout directly on clicking the logout tab on Settings page or to show a modal for confirmation. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR implements the complete settings screen. Also includes, delete keychain item implementation and proper implementation of models and ViewModels for settings.

Feedback api can't be found on backend, hence a placeholder view has been used for now. On confirmation, it will either be removed from settings or completed.

Fixes #54 

### Mocks
image

### Type of Change:
- Code
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on Simulator

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
@yugantarjain Did you intend to fix the keychain login issue here? There is still a problem logging in correctly after the app is uninstalled.

**Comment by yugantarjain** [comment]
> @yugantarjain Did you intend to fix the keychain login issue here? There is still a problem logging in correctly after the app is uninstalled.

The delete keychain code has been implemented, and is executed on log out. I was hoping if you could tell me whether that helps or not...

Also, I too had a lab to troubleshoot this issue, and have some obj-c code given by the Apple engineer. I'll try to go through the documentation again (and the code) and fix the bug for other cases too.

**Comment by sunjunkie** [comment]
The logout/login works fine but if I uninstall the app (without logging out) the issue remains. I can create a new issue for that independent of this PR. Are there other cases in which this issue occurs?
Why do you need objc code? I tested SecItemDelete + SecItemAdd in replaceKeychainItem (instead of SecItemUpdate) and it worked fine.

**Review by sunjunkie — APPROVED** [review]
I will create a new issue for the keychain update issue.

**Comment by yugantarjain** [comment]
> Why do you need objc code? I tested SecItemDelete + SecItemAdd in replaceKeychainItem (instead of SecItemUpdate) and it worked fine.

It did? That's superb! The objc code is just for reference. Yes, making a new issue seems perfect. Thanks!

**Review by ApheleiaS — APPROVED** [review]

**Pull request merged**
