### PR TITLE
fix: failing home service test fixed

### LINKED ISSUE #108: bug: Unit tests for HomeService are failing
**Describe the bug**
The unit tests in HomeTests.swift are failing.

**To Reproduce**
1. Run unit tests in HomeTests.swift.
2. See that tests are failing.

**Expected behavior**
1. Run unit tests in HomeTests.swift.
2. See that tests are passing.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 13.5

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR fixes the failing home service test. The mockJSON has been created as a string constant instead of an object and this somehow solves the problem. The test works properly (changing the assert statement fails the test).

Fixes #108 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested on Xcode.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
Looks good. Just fix the Travis and branch issues and also remove the comment in HomeTests that references the bug.

**Comment by yugantarjain** [comment]
@sunjunkie done.

**Comment by sunjunkie** [comment]
Also remove the comment in HomeTests that says there is a bug...

**Comment by yugantarjain** [comment]
> Also remove the comment in HomeTests that says there is a bug...

Oh yes, done.

**Review by sunjunkie — APPROVED** [review]

**Review by vatsalkul — APPROVED** [review]

**Pull request merged**
