### PR TITLE
feat: Report Task Comments for Violation of Code of Conduct

### LINKED ISSUE #109: feat: Implement report violation functionality
## Description
As a user, I may want to report a violation of code of conduct in current relation. So that org admins can take action towards the reported user.

### Update [Required]
- [ ] Create UI implementation of report violation
- [ ] Connect UI with report violation endpoint in the backend. [Issue](https://github.com/anitab-org/mentorship-backend/issues/709)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
6 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR implements the report violation API ([PR](https://github.com/anitab-org/mentorship-backend/pull/712)) in the app. Context menu has been used to show the 'Report This Comment' button on a task comment by another user. Tapping on the button brings up an alert to confirm/cancel the action. On confirmation, the api endpoint is used and user is notified of the result.

Note: The report violations API isn't on the server yet. The testing has been done on the local host.

Fixes #109 

### Mocks
Method 1 (Context Menu) | Method 2 (Action Sheet) | Alert
-- | -- | --
Screen Shot 2020-08-07 at 2 56 25 AM | Screen Shot 2020-08-10 at 12 07 35 AM | Screen Shot 2020-08-10 at 12 07 44 AM

### Type of Change:
- Code
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on Simulator.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
My comments so far:

1. Change "Report comment message" to "Reporting this comment will send an email to the AnitaB.org admins which will include the comment and identification of the commenter and you."  

2. So I think we need to indicate what a violation is - what is an acceptable reason to report a comment. This is something for the mentorship community to discuss (outside of GSoC).

3. Looks like the only way to report a violation is to long press on the comment. This is great but discovery is an issue. Long press is inconsistently used in iOS apps and most users don't bother to look for them. Apple's guidelines: "Offer shortcut gestures to **supplement, not replace**, interface-based navigation and actions. Whenever possible, offer a simple, **visible** way to navigate or perform an action, even if it means an extra tap or two." So there should be a visible way to report violations. At this point, there is no way to tell in the app that reporting violations is a feature.

4. It appears that marking a task complete has been moved to a long press. It's great to have that but the same issue as above applies. Also, the icon to the left of the task looks like a radio button and most users will probably expect to be able to tap that to mark a task as done. 

5. I'm thinking that the user should also be able to report violations on done tasks. Otherwise, a violator could mark a task as done to circumvent this...

**Comment by yugantarjain** [comment]
> My comments so far:
> 
> 1. Change "Report comment message" to "Reporting this comment will send an email to the AnitaB.org admins which will include the comment and identification of the commenter and you."
> 2. So I think we need to indicate what a violation is - what is an acceptable reason to report a comment. This is something for the mentorship community to discuss (outside of GSoC).
> 3. Looks like the only way to report a violation is to long press on the comment. This is great but discovery is an issue. Long press is inconsistently used in iOS apps and most users don't bother to look for them. Apple's guidelines: "Offer shortcut gestures to **supplement, not replace**, interface-based navigation and actions. Whenever possible, offer a simple, **visible** way to navigate or perform an action, even if it means an extra tap or two." So there should be a visible way to report violations. At this point, there is no way to tell in the app that reporting violations is a feature.
> 4. It appears that marking a task complete has been moved to a long press. It's great to have that but the same issue as above applies. Also, the icon to the left of the task looks like a radio button and most users will probably expect to be able to tap that to mark a task as done.
> 5. I'm thinking that the user should also be able to report violations on done tasks. Otherwise, a violator could mark a task as done to circumvent this...

1. Done
2. Yeah
3. Agreed. How about putting the comment in navigation and then giving the options in the next screen? Or, having a "..." icon and then showing an action sheet?
4. Yes, it was done since tapping now leads to the task comments page. How about a direct tap on the icon (radio button) shows the alert to mark as complete?
5. I think they can. I've just tested and a user can report a task comment no matter if it's on a To-Do task or a Done task.

**Comment by sunjunkie** [comment]
3. I am good with an ellipsis icon and action sheet

4. That sounds good.

**Comment by yugantarjain** [comment]
@sunjunkie Done.
To nicely add the ellipsis icon, the date-time text has been shifted to the next line. Task comments screen looks like this now- 

Screen Shot 2020-08-10 at 12 02 38 AM

**Comment by sunjunkie** [comment]
I'm not sure an action sheet is entirely appropriate here (since there is only one action). 

1 - I suggest either keep the action sheet for now until a UI review is done by the mentorship team (plus we may have other actions such as delete...) OR just pop up the same alert as for the long press. Let's discuss in our meeting.
2 - Change title to use title case "Actions for Comment"

**Comment by yugantarjain** [comment]
@sunjunkie title case done.

**Review by sunjunkie — DISMISSED** [review]

**Comment by sunjunkie** [comment]
@yugantarjain I did approve this but now I see there is a build issue...

**Comment by yugantarjain** [comment]
> @yugantarjain I did approve this but now I see there is a build issue...

@sunjunkie I've just updated my Xcode to 11.6, travis may be failing because of that...
I've tested it on device, it is building fine. I've also done swiftlint locally, there are no errors.

**Comment by yugantarjain** [comment]
@sunjunkie have updated travis. Build is passing now.

**Review by sunjunkie — APPROVED** [review]

**Review by vatsalkul — APPROVED** [review]
Nice work

**Pull request merged**
