### PR TITLE
feat: Relation request actions to accept, reject, cancel, and delete request

### LINKED ISSUE #86: Add request actions - accept, reject, cancel, and delete
## Description
As a user,
I need be able to accept, reject, cancel, or delete requests,
so that I can accept, reject, or delete a pending request and cancel an accepted request.

### Update [Required]
- [ ] Add accept and reject button for received pending request
- [ ] Add delete button for sent pending request
- [ ] Add cancel button for accepted requests
- [ ] Consume backend endpoints

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
Implements UI + backend consumption to accept, reject, and delete pending requests, and cancel accepted request.
Also improves backend fetching by shifting appropriate operations from init() method to onAppear instead.

Fixes: #86 

### Mocks
Screen Shot 2020-07-09 at 12 52 00 AM

### Type of Change:
- Code
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on Simulator.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
@yugantarjain There are some conflicts here to resolve.

**Comment by yugantarjain** [comment]
> @yugantarjain There are some conflicts here to resolve.

@sunjunkie resolved.

**Review by sunjunkie — CHANGES_REQUESTED** [review]
The features are working in my testing. 
 
In general, using "Confirm" is too generic. Instead use an action word that describes the action to be taken. So "Accept" (instead of Confirm), "Reject" instead of Confirm, "Delete", etc. For Cancel, we have a problem. When cancelling a relation, the alert buttons are "Cancel" and "Confirm". This may confuse the user since what they want to do is actually Cancel but instead must tap Confirm. For now, I suggest that we call this action something else, such as "*Withdraw* from Relation?"

BTW, how does one "complete" a relation?

**Comment by yugantarjain** [comment]
> The features are working in my testing.
> 
> In general, using "Confirm" is too generic. Instead use an action word that describes the action to be taken. So "Accept" (instead of Confirm), "Reject" instead of Confirm, "Delete", etc. For Cancel, we have a problem. When cancelling a relation, the alert buttons are "Cancel" and "Confirm". This may confuse the user since what they want to do is actually Cancel but instead must tap Confirm. For now, I suggest that we call this action something else, such as "_Withdraw_ from Relation?"
> 
> BTW, how does one "complete" a relation?

Okay, will do. An accepted relation gets completed when the end data passes (if not cancelled before that 😅).

**Comment by yugantarjain** [comment]
@sunjunkie also, in the mentors meeting, we (@vatsalkul @ApheleiaS) had a discussion about making the buttons to accept, reject, delete, and reject solid, i.e. adding a background. How do you feel about that?

**Comment by sunjunkie** [comment]
@yugantarjain  iOS provides a way to highlight a destructive action. See https://developer.apple.com/documentation/uikit/uialertactionstyle/uialertactionstyledestructive. Is that available in SwiftUI? Otherwise the standard is to make the destructive action red text and to set the safe action (Cancal) button as the default ( which makes it bold). Don’t do anything fancy to an alert.

**Comment by yugantarjain** [comment]
> @yugantarjain iOS provides a way to highlight a destructive action. See https://developer.apple.com/documentation/uikit/uialertactionstyle/uialertactionstyledestructive. Is that available in SwiftUI? Otherwise the standard is to make the destructive action red text and to set the safe action (Cancal) button as the default ( which makes it bold). Don’t do anything fancy to an alert.

Yes, we do have destructive alert button in SwiftUI. Should I use it for delete action?

**Comment by sunjunkie** [comment]
> > @yugantarjain iOS provides a way to highlight a destructive action. See https://developer.apple.com/documentation/uikit/uialertactionstyle/uialertactionstyledestructive. Is that available in SwiftUI? Otherwise the standard is to make the destructive action red text and to set the safe action (Cancal) button as the default ( which makes it bold). Don’t do anything fancy to an alert.
> 
> Yes, we do have destructive alert button in SwiftUI. Should I use it for delete action?

I would use it for all actions that can’t be undone. E.g Withdraw, reject, delete, etc.

**Comment by yugantarjain** [comment]
> > > @yugantarjain iOS provides a way to highlight a destructive action. See https://developer.apple.com/documentation/uikit/uialertactionstyle/uialertactionstyledestructive. Is that available in SwiftUI? Otherwise the standard is to make the destructive action red text and to set the safe action (Cancal) button as the default ( which makes it bold). Don’t do anything fancy to an alert.
> > 
> > 
> > Yes, we do have destructive alert button in SwiftUI. Should I use it for delete action?
> 
> I would use it for all actions that can’t be undone. E.g Withdraw, reject, delete, etc.

Okay

**Comment by yugantarjain** [comment]
@sunjunkie done.

**Review by sunjunkie — APPROVED** [review]

**Review by vatsalkul — APPROVED** [review]
Great! 🎉

**Pull request merged**
