### PR TITLE
Darkmode fixes

### LINKED ISSUE #124: Mentorship Logo image has white background and disrupts dark mode.
**Describe the bug**
Mentorship Logo image used in the app has white background and stays white even in dark mode disrupting the UI of Login and About screen in dark mode.

**To Reproduce**
1. Go to Login or About screen
2. Switch to Dark Mode
3. See mentorship logo with white background

**Expected behavior**
The image should have transparent background (or some other solution) and hence automatically adapt to light/dark mode.

**Screenshots**
|Light ✅|Dark ❌|
|-----|-----|
|Screen Shot 2020-08-30 at 2 39 01 PM|Screen Shot 2020-08-30 at 1 30 03 PM|

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 13.6
 - Xcode 13.6

### PR DESCRIPTION
**Pull request by aaryankotharii**
### Description
This pr solves a bug where logo's background stayed white in dark mode. This have been solved by adding a new asset without the white background. Since logo of AnitaB.org is a dark colour in the original asset, a new dark mode asset has been added for dark mode.

### Preview
Light              |  Dark
:-------------------------:|:-------------------------:
light| dark

Fixes #124 

### Type of Change:
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested on simulator.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by yugantarjain** [comment]
@aaryankotharii great work!
However, looks like you've forgotten to add the new dark mode asset...

**Comment by aaryankotharii** [comment]
> @aaryankotharii great work!
> However, looks like you've forgotten to add the new dark mode asset...

Oh sorry! Ill push it right now.

**Comment by aaryankotharii** [comment]
Yes, @yugantarjain asset has been added.

**Comment by yugantarjain** [comment]
> Yes, @yugantarjain asset has been added.

The new dark mode asset isn't perfectly aligned with the original asset. For example: when switching between light and dark mode, "Systers" text shifts its position very noticeably. Also, I guess the Font isn't the same too.

@anitab-org/mentorship-ios-maintainers do we have a .psd file for the logo that can be used to create the new dark mode asset?

**Comment by aaryankotharii** [comment]
@yugantarjain Can you please check once more.

**Comment by yugantarjain** [comment]
> @yugantarjain Can you please check once more.

Oh this is amazing! I'm approving it. Thank you!

**Review by yugantarjain — APPROVED** [review]

**Review by sunjunkie — APPROVED** [review]
Looks good! Thank you.

**Pull request merged**
