### PR TITLE
Fixed: Issue #69 - changed print statements to log statements

### LINKED ISSUE #69: refactor: Remove print statements from the code.
**Describe the bug**
There are a lot of print statements in the code. Need to remove them and add logging instead. 

**To Reproduce**
Go to the following files
- mentorship ios/Models/LoginModel.swift 
- mentorship ios/Models/HomeModel.swift
- mentorship ios/Models/MemberModel.swift

### PR DESCRIPTION
**Pull request by garima-bothra**
### Description
This PR changes print statements in LoginViewModel and MemberViewModel to log statements.

Fixes #69 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- This feature changes print statements to log statements

### How Has This Been Tested?
XCode

### Checklist:
 - [x] My PR follows the style guidelines of this project
 - [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently does not break
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by garima94921** [comment]
@vatsalkul @ApheleiaS @isabelcosta

**Comment by garima94921** [comment]
@vatsalkul

**Comment by garima-bothra** [comment]
@vatsalkul @annabauza @ApheleiaS please review this PR

**Comment by sunjunkie** [comment]
So, in the case of the 2 print statements in LoginViewModel - they don't really add any information to the log so I suggest that we delete them entirely. In the case of the 3rd item, don't log the request data but just log a statement that a request was made to the server.

**Comment by vatsalkul** [comment]
Congratulations 🎉  @garima94921 on submitting first PR for Mentorship iOS. Adding to what ginny said, replace print(token) with NSLog(token) in HomeViewModel, with some context about the information.

**Comment by garima-bothra** [comment]
@sunjunkie I've made the suggested changes, please review again

**Review by sunjunkie — APPROVED** [review]

**Review by vatsalkul — APPROVED** [review]

**Pull request merged**
