### PR TITLE
feat: Add screenshots in readme files

### LINKED ISSUE #121: docs: Update Readme with screenshots
As a user/new contributor of mentorship iOS, I want to see how the app looks like. So that I can compare it with android, flutter version of Mentorship System.

 ## Acceptance Criteria
 ### Update [Required]
 * [ ] Add 2 Screen shot in readme file
 * [ ] Add all other screenshots in docs folder having screenshots.md file
 * [ ]  Link screenshots.md file in readme.
 
 ## Definition of Done
 * [ ]  All of the required items are completed.
 * [ ]  Approval by 1 mentor.
 
 ## Estimation
1 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR showcases the project in the README file and also includes all the screenshots in a new md file in the docs folder.

Screen Shot 2020-08-27 at 12 03 34 AM

Fixes #121 

### Type of Change:
- Code
- Quality Assurance
- Outreach
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?
Tested on GitHub

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers please visit my fork to see the rendered README and new md file in the docs folder.
https://github.com/yugantarjain/mentorship-ios/tree/screenshots

**Review by ApheleiaS — DISMISSED** [review]

**Review by vatsalkul — APPROVED** [review]

**Comment by yugantarjain** [comment]
@vatsalkul I guess the Travis got stuck. I've re-requested a review.

**Review by vatsalkul — DISMISSED** [review]

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers I've updated this PR a little because Travis got stuck. Please review again.

**Comment by sunjunkie** [comment]
@yugantarjain Can you also remove the item from the Readme that states that you have to log in to the app to run the unit tests?

**Comment by yugantarjain** [comment]
@sunjunkie that has been done in the [Robust Service Tests PR](https://github.com/anitab-org/mentorship-ios/pull/120)

**Comment by sunjunkie** [comment]
Of course! 🥴

**Review by sunjunkie — APPROVED** [review]

**Review by ApheleiaS — APPROVED** [review]
Looks good to me!

**Comment by yugantarjain** [comment]
@anitab-org/mentorship-ios-maintainers this PR has been approved. Needs to be merged.

**Pull request merged**
