### PR TITLE
Create README.md

### LINKED ISSUE #1: Add a Readme file to the repository
## Description
As a Developer,
I need to understand what this project is about,
so that I can contribute to the development of this project.

### Update [Required]
- [ ] Add new Readme file

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
README file added so that developers interested in learning and contributing to the project can do it easily.

Fixes #1 

### Type of Change:
- Documentation

### How Has This Been Tested?
Checked and proofread multiple times.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by sunjunkie — COMMENTED** [review]
This is a good start. You can also look at Powerup repos for other formats. I've answered your questions in the issue and will check with May about any new standards.

**Comment by yugantarjain** [comment]
Hi, I've updated the README. I believe it is ready to be merged now. 
I've used content from both - mentorship-android and powerup-ios repositories. Please have a look and let me know if it's alright. Thanks!

**Comment by sunjunkie** [comment]
Looks great. I just have 2 minor changes. 1 - there is no space before a "." at the end of a sentence. 2 - You don't need to use the word "kindly" in technical documentation. :-)

**Comment by yugantarjain** [comment]
Updated. Omitted the word "kindly" and italicized ".xcodeproject" (I assume point 1 is about this).

**Comment by sunjunkie** [comment]
Everything looks great. However, we do follow a pull request template so could you add the template text to the PR description. You can see the template at https://github.com/anitab-org/mentorship-ios/blob/develop/.github/PULL_REQUEST_TEMPLATE.md.  I'm sorry for this rework - I should have explained this sooner.

**Comment by yugantarjain** [comment]
No problem. I've made the description as per the template. Thanks

**Review by sunjunkie — APPROVED** [review]

**Pull request merged**
