### PR TITLE
Navigate from members list screen to new screen

### LINKED ISSUE #32: feat: Navigate from members list to details screen for a member
## Description
As a user,
I need to choose a member from the list of members,
so that I can the details for that member.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] User can select a member from the list
- [ ] User can navigate to a details screen for that member.
- [ ] User can navigate back from the details screen to the member list screen.
- [ ] UI follows project UI guidelines

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
Adds navigation from members list screen to a new screen. Members screen UI updated with disclosure indicator. This PR also includes a small update to gitignore file.

Fixes #32 

### Mock ups
Screen Shot 2020-06-07 at 5 05 32 PM

### Type of Change:
- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on simulator.

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
There are 3 files in the PR that shouldn't be there. (Yes we do need that addition to the .gitignore). 
Also, how do I build and run with the backend? Do I need to do something special. I don't see any data in the Members list.
Please include preview data in future PRs.

**Comment by yugantarjain** [comment]
Yes, there's a caveat. The members screen is the hosting view right now, so the token required for the backend isn't there (we get that from login screen). I'm working on fixing this and and establishing proper flow of the app.

**Comment by sunjunkie** [comment]
OK. Can you remove the 3 files from the PR? Then I'll merge.

**Comment by yugantarjain** [comment]
I think the PR removes those files. That is a required step for gitignore to work properly.
I guess git rm --cached filepath caused that.

**Comment by sunjunkie** [comment]
Oh, yes. I see now.

**Review by sunjunkie — APPROVED** [review]

**Comment by annabauza** [comment]
@sunjunkie @yugantarjain do not merge when Travis fail...

**Comment by sunjunkie** [comment]
@annabauza Travis fails due to Swiftlint errors. I took a look and couldn’t see the problem so I plan to look at swiftlint in more detail. I did not want to hold up the merge just for swiftlint since this is a very recent requirement. But, yes, I agree that we should not normally merge on a Travis fail.

**Comment by annabauza** [comment]
I left information how to solve it in channel.

**Pull request merged**
