### PR TITLE
feat: Login/SignUp View Model Unit Tests

### LINKED ISSUE #9: Create unit tests for user login/registration
## Description
As a developer, I need to ensure the quality of app, so that It will not crash when in use.

### Update [Required]
- [ ] Create unit tests for user login/registration.
- [ ] Add different test cases to test the behaviour of user login/registration screen.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR includes some unit tests for the sign up view model.

Fixes #9 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Xcode

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
Looks like "MentorshipTests.swift" is still referenced in the project file.

**Comment by yugantarjain** [comment]
> Looks like "MentorshipTests.swift" is still referenced in the project file.

"MentorshipTests.swift" has a testDonwloadWebData method. It tests our backend server url through an actual network request.

**Comment by sunjunkie** [comment]
Where is the file? It is deleted in this PR.

**Comment by yugantarjain** [comment]
> Where is the file? It is deleted in this PR.

@sunjunkie Just realized. Fixed.

**Comment by sunjunkie** [comment]
@yugantarjain Looks good and the mark comments are a definite improvement. Just one issue to fix (an incorrect assertion).

**Comment by yugantarjain** [comment]
> @yugantarjain Looks good and the mark comments are a definite improvement. Just one issue to fix (an incorrect assertion).

@sunjunkie Fixed. Thanks!

**Review by sunjunkie — APPROVED** [review]

**Review by ApheleiaS — APPROVED** [review]

**Pull request merged**
