### PR TITLE
feat: Relation Screen UI

### LINKED ISSUE #74: feat: Build UI for tasks screen
## Description
As a user, I need to complete my tasks given by mentor, so that I can successfully complete a relationship.

### Update [Required]
- [ ] Make UI for tasks

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by yugantarjain**
### Description
This PR implements the Relation(Tasks) Screen UI. 

Fixes #74 

### Mocks
Tasks List | Add Task
---------- | ----------
Screen Shot 2020-07-01 at 3 47 05 AM | Screen Shot 2020-07-04 at 6 18 35 PM

### Type of Change:
- Code
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested on Simulator

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sunjunkie** [comment]
@yugantarjain  The Add Task screen looks very strange. What are you blurring and why is it necessary? Why don't you present a sheet?

**Comment by yugantarjain** [comment]
> @yugantarjain The Add Task screen looks very strange. What are you blurring and why is it necessary? Why don't you present a sheet?

@sunjunkie a sheet seems like an overkill to me to have a single text field and a button. Can we do something else maybe or should I go ahead and implement it as a sheet? What do you think?

**Comment by vatsalkul** [comment]
Maybe we can do something like this. Alert view with textfield, but we need to check how to implement this in SwiftUI.
Screenshot 2020-07-04 at 5 12 55 PM

**Comment by yugantarjain** [comment]
> Maybe we can do something like this. Alert view with textfield, but we need to check how to implement this in SwiftUI.
> Screenshot 2020-07-04 at 5 12 55 PM

As far as I know, an alert with text field is not available on SwiftUI yet.

**Comment by vatsalkul** [comment]
@yugantarjain For that, we need to make a wrapper around UIKit alerts.
Then sheets would be okay.
Btw, if you want to learn about alerts with textfield in swiftUI, here is the link: https://www.objc.io/blog/2020/04/21/swiftui-alert-with-textfield/

**Comment by yugantarjain** [comment]
Okay, I'll implement the sheet then.

**Comment by yugantarjain** [comment]
@ApheleiaS @sunjunkie @vatsalkul @annabauza have implemented sheet.

**Comment by sunjunkie** [comment]
> > Maybe we can do something like this. Alert view with textfield, but we need to check how to implement this in SwiftUI.
> > Screenshot 2020-07-04 at 5 12 55 PM
> 
> As far as I know, an alert with text field is not available on SwiftUI yet.

This is for adding data to the relation. An alert is not appropriate here.

**Review by sunjunkie — APPROVED** [review]

**Review by vatsalkul — APPROVED** [review]
Looks good Now!

**Pull request merged**
